// Generated by gencpp from file sensor_server/GetSensValResponse.msg
// DO NOT EDIT!


#ifndef SENSOR_SERVER_MESSAGE_GETSENSVALRESPONSE_H
#define SENSOR_SERVER_MESSAGE_GETSENSVALRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace sensor_server
{
template <class ContainerAllocator>
struct GetSensValResponse_
{
  typedef GetSensValResponse_<ContainerAllocator> Type;

  GetSensValResponse_()
    : val(0)  {
    }
  GetSensValResponse_(const ContainerAllocator& _alloc)
    : val(0)  {
    }



   typedef int64_t _val_type;
  _val_type val;




  typedef boost::shared_ptr< ::sensor_server::GetSensValResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::sensor_server::GetSensValResponse_<ContainerAllocator> const> ConstPtr;

}; // struct GetSensValResponse_

typedef ::sensor_server::GetSensValResponse_<std::allocator<void> > GetSensValResponse;

typedef boost::shared_ptr< ::sensor_server::GetSensValResponse > GetSensValResponsePtr;
typedef boost::shared_ptr< ::sensor_server::GetSensValResponse const> GetSensValResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::sensor_server::GetSensValResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::sensor_server::GetSensValResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace sensor_server

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/jade/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::sensor_server::GetSensValResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::sensor_server::GetSensValResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sensor_server::GetSensValResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sensor_server::GetSensValResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sensor_server::GetSensValResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sensor_server::GetSensValResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::sensor_server::GetSensValResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "58ba147ce3095b36344060f1e5dd0b05";
  }

  static const char* value(const ::sensor_server::GetSensValResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x58ba147ce3095b36ULL;
  static const uint64_t static_value2 = 0x344060f1e5dd0b05ULL;
};

template<class ContainerAllocator>
struct DataType< ::sensor_server::GetSensValResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "sensor_server/GetSensValResponse";
  }

  static const char* value(const ::sensor_server::GetSensValResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::sensor_server::GetSensValResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 val\n\
\n\
";
  }

  static const char* value(const ::sensor_server::GetSensValResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::sensor_server::GetSensValResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.val);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct GetSensValResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::sensor_server::GetSensValResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::sensor_server::GetSensValResponse_<ContainerAllocator>& v)
  {
    s << indent << "val: ";
    Printer<int64_t>::stream(s, indent + "  ", v.val);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SENSOR_SERVER_MESSAGE_GETSENSVALRESPONSE_H
