// Generated by gencpp from file sensor_server/GetSensValRequest.msg
// DO NOT EDIT!


#ifndef SENSOR_SERVER_MESSAGE_GETSENSVALREQUEST_H
#define SENSOR_SERVER_MESSAGE_GETSENSVALREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace sensor_server
{
template <class ContainerAllocator>
struct GetSensValRequest_
{
  typedef GetSensValRequest_<ContainerAllocator> Type;

  GetSensValRequest_()
    : name()
    , data()  {
    }
  GetSensValRequest_(const ContainerAllocator& _alloc)
    : name(_alloc)
    , data(_alloc)  {
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _name_type;
  _name_type name;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _data_type;
  _data_type data;




  typedef boost::shared_ptr< ::sensor_server::GetSensValRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::sensor_server::GetSensValRequest_<ContainerAllocator> const> ConstPtr;

}; // struct GetSensValRequest_

typedef ::sensor_server::GetSensValRequest_<std::allocator<void> > GetSensValRequest;

typedef boost::shared_ptr< ::sensor_server::GetSensValRequest > GetSensValRequestPtr;
typedef boost::shared_ptr< ::sensor_server::GetSensValRequest const> GetSensValRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::sensor_server::GetSensValRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::sensor_server::GetSensValRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace sensor_server

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/jade/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::sensor_server::GetSensValRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::sensor_server::GetSensValRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sensor_server::GetSensValRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sensor_server::GetSensValRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sensor_server::GetSensValRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sensor_server::GetSensValRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::sensor_server::GetSensValRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0a150dc399b6cef3706553ca3c336ddf";
  }

  static const char* value(const ::sensor_server::GetSensValRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0a150dc399b6cef3ULL;
  static const uint64_t static_value2 = 0x706553ca3c336ddfULL;
};

template<class ContainerAllocator>
struct DataType< ::sensor_server::GetSensValRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "sensor_server/GetSensValRequest";
  }

  static const char* value(const ::sensor_server::GetSensValRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::sensor_server::GetSensValRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string name\n\
string data\n\
";
  }

  static const char* value(const ::sensor_server::GetSensValRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::sensor_server::GetSensValRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.name);
      stream.next(m.data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct GetSensValRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::sensor_server::GetSensValRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::sensor_server::GetSensValRequest_<ContainerAllocator>& v)
  {
    s << indent << "name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.name);
    s << indent << "data: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.data);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SENSOR_SERVER_MESSAGE_GETSENSVALREQUEST_H
