// Generated by gencpp from file sensor_server/GetSensVal.msg
// DO NOT EDIT!


#ifndef SENSOR_SERVER_MESSAGE_GETSENSVAL_H
#define SENSOR_SERVER_MESSAGE_GETSENSVAL_H

#include <ros/service_traits.h>


#include <sensor_server/GetSensValRequest.h>
#include <sensor_server/GetSensValResponse.h>


namespace sensor_server
{

struct GetSensVal
{

typedef GetSensValRequest Request;
typedef GetSensValResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetSensVal
} // namespace sensor_server


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::sensor_server::GetSensVal > {
  static const char* value()
  {
    return "1bc3537bb8034a7562e9cc5973528637";
  }

  static const char* value(const ::sensor_server::GetSensVal&) { return value(); }
};

template<>
struct DataType< ::sensor_server::GetSensVal > {
  static const char* value()
  {
    return "sensor_server/GetSensVal";
  }

  static const char* value(const ::sensor_server::GetSensVal&) { return value(); }
};


// service_traits::MD5Sum< ::sensor_server::GetSensValRequest> should match 
// service_traits::MD5Sum< ::sensor_server::GetSensVal > 
template<>
struct MD5Sum< ::sensor_server::GetSensValRequest>
{
  static const char* value()
  {
    return MD5Sum< ::sensor_server::GetSensVal >::value();
  }
  static const char* value(const ::sensor_server::GetSensValRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::sensor_server::GetSensValRequest> should match 
// service_traits::DataType< ::sensor_server::GetSensVal > 
template<>
struct DataType< ::sensor_server::GetSensValRequest>
{
  static const char* value()
  {
    return DataType< ::sensor_server::GetSensVal >::value();
  }
  static const char* value(const ::sensor_server::GetSensValRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::sensor_server::GetSensValResponse> should match 
// service_traits::MD5Sum< ::sensor_server::GetSensVal > 
template<>
struct MD5Sum< ::sensor_server::GetSensValResponse>
{
  static const char* value()
  {
    return MD5Sum< ::sensor_server::GetSensVal >::value();
  }
  static const char* value(const ::sensor_server::GetSensValResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::sensor_server::GetSensValResponse> should match 
// service_traits::DataType< ::sensor_server::GetSensVal > 
template<>
struct DataType< ::sensor_server::GetSensValResponse>
{
  static const char* value()
  {
    return DataType< ::sensor_server::GetSensVal >::value();
  }
  static const char* value(const ::sensor_server::GetSensValResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SENSOR_SERVER_MESSAGE_GETSENSVAL_H
