(cl:defpackage sensor_server-srv
  (:use )
  (:export
   "ADDTWOINTS"
   "<ADDTWOINTS-REQUEST>"
   "ADDTWOINTS-REQUEST"
   "<ADDTWOINTS-RESPONSE>"
   "ADDTWOINTS-RESPONSE"
   "GETSENSVAL"
   "<GETSENSVAL-REQUEST>"
   "GETSENSVAL-REQUEST"
   "<GETSENSVAL-RESPONSE>"
   "GETSENSVAL-RESPONSE"
  ))

